version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa-faq-app
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      INGEST_API_KEY: ${INGEST_API_KEY:-your-api-key-here}
      INGEST_WEBHOOK_SECRET: ${INGEST_WEBHOOK_SECRET:-your-webhook-secret-here}
      NODE_ENV: production
    ports:
      - "3000:3000"
